version: '3.7'

services:
  calculatorservice:
    container_name: calculator
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      User: calculator
      Password: postgres
      Dbname: calculator
      Host: host.docker.internal
    labels:
      collect_logs_using_filebeat: "true"
      convert_logs_to_json_object: "true"
    networks: 
      - calculatornetwork

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.6.2
    hostname: filebeat
    volumes:
      - ./elk/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - filebeat_data:/usr/share/filebeat/data:rw
    user: root
    restart: on-failure
    networks:
      - calculatornetwork

volumes: 
  filebeat_data:
