version: '3.7'

services:
  bankservice:
    container_name: bankservice
    image: docker.pkg.github.com/cd-jump-start/service-dep-bankservice/bankservice:latest
    ports:
      - 8082:8082
    environment:
      - server.port=8082
    networks:
      - calculatornetwork

  fraudservice:
    container_name: fraudservice
    image: docker.pkg.github.com/cd-jump-start/service-dep-fraudservice/fraudservice:latest
    ports:
      - 8083:8083
    environment:
      - server.port=8083
    networks:
      - calculatornetwork